// ================================================
// AUTH SETUP — Interactive credential setup script
// Run: npx ts-node src/auth/setup.ts
// ================================================

import 'dotenv/config';
import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { AuthService } from './AuthService';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}

async function setup(): Promise<void> {
  console.log(`
  ╔══════════════════════════════════════════════╗
  ║     🔐 SETUP DE SEGURANÇA                    ║
  ║     Polymarket AI Trader                      ║
  ╚══════════════════════════════════════════════╝
  `);

  // Get email
  const email = await question('📧 Seu e-mail: ');
  if (!email || !email.includes('@')) {
    console.error('❌ E-mail inválido.');
    process.exit(1);
  }

  // Get password
  const password = await question('🔑 Sua senha (mín. 8 caracteres): ');
  if (!password || password.length < 8) {
    console.error('❌ Senha deve ter no mínimo 8 caracteres.');
    process.exit(1);
  }

  // Confirm password
  const confirmPassword = await question('🔑 Confirme a senha: ');
  if (password !== confirmPassword) {
    console.error('❌ Senhas não conferem.');
    process.exit(1);
  }

  // Hash password
  console.log('\n⏳ Gerando hash seguro da senha...');
  const passwordHash = await AuthService.hashPassword(password);

  // Generate JWT secret
  const jwtSecret = crypto.randomBytes(64).toString('hex');

  // Update .env file
  const envPath = path.join(process.cwd(), '.env');
  let envContent = '';

  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf-8');
  }

  // Remove old auth entries if they exist
  envContent = envContent
    .split('\n')
    .filter(line =>
      !line.startsWith('AUTH_EMAIL=') &&
      !line.startsWith('AUTH_PASSWORD_HASH=') &&
      !line.startsWith('JWT_SECRET=')
    )
    .join('\n');

  // Add auth section
  const authSection = `
# ================================================
# AUTHENTICATION (generated by setup script)
# ================================================
AUTH_EMAIL=${email.toLowerCase().trim()}
AUTH_PASSWORD_HASH=${passwordHash}
JWT_SECRET=${jwtSecret}
`;

  envContent = envContent.trimEnd() + '\n' + authSection;
  fs.writeFileSync(envPath, envContent);

  console.log(`
  ✅ ════════════════════════════════════════════
  
  Credenciais configuradas com sucesso!
  
  📧 E-mail: ${email}
  🔒 Senha: ${'*'.repeat(password.length)} (hashificada com bcrypt)
  🔑 JWT Secret: ${jwtSecret.slice(0, 16)}... (64 bytes)
  
  📁 Salvo em: ${envPath}
  
  ⚠️  NUNCA compartilhe o arquivo .env!
  ⚠️  NUNCA commit o .env no Git!
  
  Agora rode: npm run dev
  Acesse: http://localhost:3000/login
  
  ✅ ════════════════════════════════════════════
  `);

  rl.close();
  process.exit(0);
}

setup().catch((err) => {
  console.error('Erro no setup:', err);
  process.exit(1);
});
